spring.application.name=yootiful-vectordbs
spring.output.ansi.enabled=always

spring.docker.compose.lifecycle-management=start_only

spring.datasource.password=admin
spring.datasource.username=admin
spring.datasource.url=jdbc:postgresql://localhost/clothing_store

#spring.ai.vectorstore.pgvector.initialize-schema=true
#spring.datasource.initialize=true

spring.ai.ollama.embedding.model=rjmalagon/gte-qwen2-1.5b-instruct-embed-f16:latest
